FROM docker:dind

ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go

RUN apk add --update \
	bash \
	go \
	git \
	gcc \
	jq \
	libc-dev \
	libgcc \
	make \
	&& rm -rf /var/cache/apk/*

# install bats
RUN cd /tmp \
    && git clone https://github.com/sstephenson/bats.git \
    && ./bats/install.sh /usr/local \
	&& rm -rf /tmp/bats

# Get useful and necessary Hub images so we can "docker load" locally instead of pulling
ADD https://raw.githubusercontent.com/docker/docker/master/contrib/download-frozen-image-v2.sh /usr/local/bin/download-frozen-image-v2.sh
RUN chmod +x /usr/local/bin/download-frozen-image-v2.sh \
	&& sleep 3 \
	&& download-frozen-image-v2.sh /docker-frozen-images \
	jess/httpie:latest@sha256:be198939d7104cc73a84604d9532c984205bd6f9b35f108d7f57c380d5a43adf \
	jess/tor-router:latest@sha256:8dfcaed4eba3ed53c066c62aaafc542da068f488a270a15253df7f87e9502aef
# see also "hack/.ensure-frozen-images" (which needs to be updated any time this list is)

COPY . /go/src/github.com/jfrazelle/onion

WORKDIR /go/src/github.com/jfrazelle/onion

RUN go get -d -v github.com/jfrazelle/onion \
	&& go build -o /usr/bin/onion .

ENTRYPOINT [ "dind" ]
CMD [ "hack/test.sh" ]
