FROM docker:dind

ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go:/go/src/github.com/jfrazelle/onion/vendor

RUN apk add --update \
	bash \
	go \
	git \
	gcc \
	jq \
	libc-dev \
	libgcc \
	make \
	&& rm -rf /var/cache/apk/*

# install bats
RUN cd /tmp \
    && git clone https://github.com/sstephenson/bats.git \
    && ./bats/install.sh /usr/local \
	&& rm -rf /tmp/bats

# install golint
RUN go get github.com/golang/lint/golint

# Get useful and necessary Hub images so we can "docker load" locally instead of pulling
ADD https://raw.githubusercontent.com/docker/docker/master/contrib/download-frozen-image-v2.sh /usr/local/bin/download-frozen-image-v2.sh
RUN chmod +x /usr/local/bin/download-frozen-image-v2.sh \
	&& sleep 3 \
	&& download-frozen-image-v2.sh /docker-frozen-images \
	jess/curl:latest@sha256:2fb32907a95824a7a45bcf09acce5256b3b7ad71f8cce05216e3e0d39e6351ac \
	jess/httpie:latest@sha256:be198939d7104cc73a84604d9532c984205bd6f9b35f108d7f57c380d5a43adf \
	jess/tor-router:latest@sha256:3201557e96210a609ca26cbaa573162045882cb23a202a7dca895042383b4ca7 \
	nginx:latest@sha256:0a8bad8dfc80e38ccdd09c41d4efd2547fa9d6d58d8706431952a2ef312e2034
# see also "hack/.ensure-frozen-images" (which needs to be updated any time this list is)

COPY . /go/src/github.com/jfrazelle/onion

WORKDIR /go/src/github.com/jfrazelle/onion

RUN go build -o /usr/bin/onion .

ENTRYPOINT [ "dind" ]
CMD [ "hack/test.sh" ]
